In [1]:
import pandas as pd

In [3]:
df_results = pd.read_csv(r'C:\Users\bartd\Documents\Erasmus_\Jaar 4\Master Econometrie\Thesis\Optimal Trees\StrongTree\Results\paper results\train.csv')

In [16]:
df_results.head(100)

,approach,dataset,nrow,depth,lambda,time_limit,status,obj_value,train_acc,gap,node_count,solving_time,cb_time_int,cb_time_int_suc,cb_counter_int,cb_counter_int_suc,test_acc,eval_acc,sample,regularization
0,BinOCT,soybean-small,23,2,0.0,3600,101,0.0,1.000000,0.0,641,0.245012,0.0,0.0,0,0,1.000000,1.000000,1,False
1,BinOCT,soybean-small,23,2,0.0,3600,101,0.0,1.000000,0.0,1016,0.321704,0.0,0.0,0,0,1.000000,1.000000,2,False
2,BinOCT,soybean-small,23,2,0.0,3600,101,0.0,1.000000,0.0,170,0.105450,0.0,0.0,0,0,1.000000,0.916667,3,False
3,BinOCT,soybean-small,23,2,0.0,3600,101,0.0,1.000000,0.0,740,0.515454,0.0,0.0,0,0,1.000000,1.000000,4,False
4,BinOCT,soybean-small,23,2,0.0,3600,101,0.0,1.000000,0.0,514,0.668584,0.0,0.0,0,0,1.000000,1.000000,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BinOCT,monk2,84,5,0.0,3600,107,5.0,0.940476,1.0,4547915,3600.000000,0.0,0.0,0,0,0.558140,0.690476,1,False
96,BinOCT,monk2,84,5,0.0,3600,107,7.0,0.916667,1.0,4022786,3600.000000,0.0,0.0,0,0,0.395349,0.571429,2,False
97,BinOCT,monk2,84,5,0.0,3600,107,5.0,0.940476,1.0,2948069,3600.000000,0.0,0.0,0,0,0.604651,0.523810,3,False
98,BinOCT,monk2,84,5,0.0,3600,107,5.0,0.940476,1.0,4486491,3600.000000,0.0,0.0,0,0,0.534884,0.666667,4,False
99,BinOCT,monk2,84,5,0.0,3600,107,6.0,0.928571,1.0,3857555,3600.000000,0.0,0.0,0,0,0.534884,0.619048,5,False

In [25]:
df_results['solved_boolean'] = df_results.solving_time < 3600
df_results['started_boolean'] = df_results.solving_time != 0

['balance-scale',
 'breast-cancer',
 'car_evaluation',
 'kr-vs-kp',
 'monk-1',
 'soybean-small']

In [48]:
select_datasets = ['balance-scale', 'breast-cancer', 'car-evaluation', 'kr-vs-kp', 'monk1', 'soybean-small']
locator = [dataset in select_datasets for dataset in df_results.dataset]
df_results_subset = df_results.loc[locator,:]

                            sum                                            \
                         solved                    started_boolean
approach             BendersOCT BinOCT FlowOCT OCT      BendersOCT BinOCT
dataset        depth
balance-scale  2             50      5      50  50              50      5
               3             50      0      50   0              50      5
               4              5      0       0   0              50      5
               5              0      0       0   0              50      5
breast-cancer  2             50      5      50  50              50      5
               3             11      0       9   4              50      5
               4              5      0       5   1              50      5
               5              5      0       5   0              50      5
car-evaluation 2             50      5      50  48              50      5
               3              4      0       0   0              50      5
               4              0      0       0   0              50      5
               5              0      0       0   0              50      5
kr-vs-kp       2             50      5      50   0              50      5
               3              0      0       0   0              50      5
               4              0      0       0   0              50      5
               5              0      0       0   0              50      5
monk1          2             50      5      50  50              50      5
               3             50      5      50  48              50      5
               4             50      5      50  49              50      5
               5             50      5      50  31              50      5
soybean-small  2             49      5      50  50              49      5
               3             50      5      50  50              50      5
               4             50      5      50  50              50      5
               5             50      5      50  50              50      5



approach             FlowOCT OCT
dataset        depth
balance-scale  2          50  50
               3          50  50
               4          50  49
               5          50  50
breast-cancer  2          50  50
               3          50  50
               4          50  50
               5          50  50
car-evaluation 2          50  50
               3          50  50
               4          50  50
               5          50  50
kr-vs-kp       2          50  50
               3          50  50
               4          50  50
               5          50  50
monk1          2          50  50
               3          50  50
               4          50  50
               5          50  50
soybean-small  2          50  50
               3          50  50
               4          50  50
               5          50  50

In [65]:
df_results_subset.pivot_table(values = ['started_boolean', 'solved'], index = ['dataset', 'depth'], columns = 'approach', aggfunc=['sum'])
df_to_latex = df_results_subset.pivot_table(values = ['solved'], index = ['dataset', 'depth'], columns = 'approach', aggfunc=['sum'])
print(df_to_latex.to_latex())

\begin{tabular}{llrrrr}
\toprule
              & {} & \multicolumn{4}{l}{sum} \\
              & {} & \multicolumn{4}{l}{solved} \\
              & approach & BendersOCT & BinOCT & FlowOCT & OCT \\
dataset & depth &            &        &         &     \\
\midrule
balance-scale & 2 &         50 &      5 &      50 &  50 \\
              & 3 &         50 &      0 &      50 &   0 \\
              & 4 &          5 &      0 &       0 &   0 \\
              & 5 &          0 &      0 &       0 &   0 \\
breast-cancer & 2 &         50 &      5 &      50 &  50 \\
              & 3 &         11 &      0 &       9 &   4 \\
              & 4 &          5 &      0 &       5 &   1 \\
              & 5 &          5 &      0 &       5 &   0 \\
car-evaluation & 2 &         50 &      5 &      50 &  48 \\
              & 3 &          4 &      0 &       0 &   0 \\
              & 4 &          0 &      0 &       0 &   0 \\
              & 5 &          0 &      0 &       0 &   0 \\
kr-vs-kp & 2 &         50 &      5 &      50 &   0 \\
              & 3 &          0 &      0 &       0 &   0 \\
              & 4 &          0 &      0 &       0 &   0 \\
              & 5 &          0 &      0 &       0 &   0 \\
monk1 & 2 &         50 &      5 &      50 &  50 \\
              & 3 &         50 &      5 &      50 &  48 \\
              & 4 &         50 &      5 &      50 &  49 \\
              & 5 &         50 &      5 &      50 &  31 \\
soybean-small & 2 &         49 &      5 &      50 &  50 \\
              & 3 &         50 &      5 &      50 &  50 \\
              & 4 &         50 &      5 &      50 &  50 \\
              & 5 &         50 &      5 &      50 &  50 \\
\bottomrule
\end{tabular}

In [51]:
pivot_solving_time = df_results_subset.pivot_table(values = ['solving_time'], index = ['dataset', 'depth'], columns = 'approach', aggfunc=['sum'])

In [55]:
total_running_time = pivot_solving_time.sum().sum()
total_running_time/(60*60*24)
#Almost 80 days

79.443154789179